<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenVisionLab.Machine.Simulation</RootNamespace>
    <AssemblyName>OpenVisionLab.Machine.Simulation</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenVisionLab.Machine.Core\OpenVisionLab.Machine.Core.csproj" />
    <ProjectReference Include="..\OpenVisionLab.Machine.IO\OpenVisionLab.Machine.IO.csproj" />
    <ProjectReference Include="..\OpenVisionLab.Machine.Sequence\OpenVisionLab.Machine.Sequence.csproj" />
  </ItemGroup>

</Project>
