<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenVisionLab.Machine.IO</RootNamespace>
    <AssemblyName>OpenVisionLab.Machine.IO</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenVisionLab.Machine.Core\OpenVisionLab.Machine.Core.csproj" />
  </ItemGroup>

</Project>