<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenVisionLab.Machine.Infrastructure</RootNamespace>
    <AssemblyName>OpenVisionLab.Machine.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenVisionLab.Integration.Contracts" Version="[0.2.0-alpha.3]" />
    <PackageReference Include="OpenVisionLab.Integration.Transport.Tcp" Version="[0.1.0-alpha.3]" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenVisionLab.Machine.Vision\OpenVisionLab.Machine.Vision.csproj" />
  </ItemGroup>

</Project>
