<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenVisionLab.Machine.Infrastructure</RootNamespace>
    <AssemblyName>OpenVisionLab.Machine.Infrastructure</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenVisionLab.Machine.Vision\OpenVisionLab.Machine.Vision.csproj" />
  </ItemGroup>

</Project>
