<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>OpenVisionLab.Machine.Persistence</RootNamespace>
    <AssemblyName>OpenVisionLab.Machine.Persistence</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpenVisionLab.Machine.Core.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenVisionLab.Machine.Core\OpenVisionLab.Machine.Core.csproj" />
  </ItemGroup>

</Project>
